<?php
	include_once('header.php');
?>

<html>
<head>
	<title>privacy and policy</title>
	<link rel="stylesheet" href="style1.css">
</head>
<body>
	<div id="privacy1">
	      <img src="images/privacy.png"height="55%" width="100%">
	</div>
    <div id="privacy2">
		 <h1 style="font-size:40px;color: #006699;"><b>HOW DO WE DEAL WITH YOUR 
		 PRIVACY</b></h1>
		 
		<div class="privacy2-l"> 
        <img src="images/privacy3.jpg"height="60%" width="95%">
		</div>
		
		<div class="privacy2-r"> 
			<h4 style= "font-size:30" >This Privacy Policy describes Our policies and
			procedures on the collection, use and disclosure of Your information when You
			use the Service and tells You about Your privacy rights and how the law protects You.

            We use Your Personal data to provide and improve the Service. By using the Service,
			You agree to the collection and use of information in accordance with this Privacy
			Policy.</h4>
		</div>

    </div>
	<div id="privacy3">
		<h1 style="font-size:40px;color: #006699; padding-bottom:25px">Interpretation and Definitions Interpretation
		 </b></h1>
		<h4 style= "font-size:30; padding-bottom:25px;">The words of which the initial letter is capitalized have 
		meanings defined under the following conditions. The following definitions shall have 
		the same meaning regardless of whether they appear in singular or in plural.</h4>
		
		<h1 style="font-size:40px;color: #006699; padding-bottom:25px">Definitions
		 </b></h1>
		 
		 
		 
		 
		 <h4 style= "font-size:30;  padding-bottom:10px;">For the purposes of this Privacy Policy:</h4>
         <h4 style= "font-size:30;">
		 <li><b>Account</b> means a unique account created for You to access our Service or parts of 
		 our Service.</li><br>

         <li><b>Affiliate</b> means an entity that controls, is controlled by or is under common 
		 control with a party, where “control” means ownership of 50% or more of the shares, 
		 equity interest or other securities entitled to vote for election of directors or 
		 other managing authority.</li><br>

        <li><b>Company</b> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) 
		refers to Touchstone Educationals LLP, SCO 88-89, Sector 17 C, Chandigarh 160017, INDIA.</li><br>
        
		<li><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other 
		device by a website, containing the details of Your browsing history on that website 
		among its many uses.</li><br>
		
		<li><b>country</b> refers to: Chandigarh, India</li><br>

        <li><b>Device</b> means any device that can access the Service such as a computer, a 
	   cellphone or a digital tablet.</li><br>

        <li><b>Personal</b> Data is any information that relates to an identified or identifiable
		individual.</li><br>

        <li><b>Service</b> refers to the Website.</li><br>

        <li><b>Service</b> Provider means any natural or legal person who processes the data on 
		behalf of the Company. It refers to third-party companies or individuals employed by
		the Company to facilitate the Service, to provide the Service on behalf of the Company,
		to perform services related to the Service or to assist the Company in analyzing how 
		the Service is used.</li><br>

        <li><b>Usage</b> Data refers to data collected automatically, either generated by the use of 
		the Service or from the Service infrastructure itself (for example, the duration of a
		page visit).</li><br>

        <li><b>You</b> means the individual accessing or using the Service, or the company, 
		or other legal entity on behalf of which such individual is accessing or using the
		Service, as applicable.</li><br>
</h4>
 
    <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Collecting and Using Your Personal Data
		 </b></h1>
    <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Types of Data Collected</h1>
    <h1 style="font-size:35px;color: #006699; padding-bottom:25px"><b>Personal Data</h1>
	<h4 style= "font-size:30; padding-bottom:25px;">While using Our Service, We may ask You to
	provide Us with certain personally identifiable information that can be used to contact or 
	identify You. Personally identifiable information may include, but is not limited to:</h4>
	<h4 style= "font-size:30;">
	<li>Email address</li> <br>
	<li>First name and last name</li><br>
    <li>Phone number</li><br>
	<li>Address, State, Province, ZIP/Postal code, City</li><br>
    <li>Usage Data</li><br></h4>

    <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Usage Data</b></h1>
    <h4 style= "font-size:30;">Usage Data is collected automatically when using the Service.<br><br>
    Usage Data may include information such as Your Device’s Internet Protocol address 
	(e.g. IP address), browser type, browser version, the pages of our Service that You visit, 
	the time and date of Your visit, the time spent on those pages, unique device identifiers 
	and other diagnostic data.<br><br>

    When You access the Service by or through a mobile device, We may collect certain
	information automatically, including, but not limited to, the type of mobile device You 
	use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile
	operating system, the type of mobile Internet browser You use, unique device identifiers 
	and other diagnostic data.<br><br>

   We may also collect information that Your browser sends whenever You visit our Service or 
   when You access the Service by or through a mobile device.<br><br></h4>

   
   <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Tracking Technologies and
   Cookies</b></h1>
   <h4 style= "font-size:30;">We use Cookies and similar tracking technologies to track the 
   activity on Our Service and store certain information. Tracking technologies used are 
   beacons, tags, and scripts to collect and track information and to improve and analyze 
   Our Service. The technologies We use may include:<br><br>
   <li><b>Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. 
   You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is 
   being sent. However, if You do not accept Cookies, You may not be able to use some parts
   of our Service. Unless you have adjusted Your browser setting so that it will refuse
   Cookies, our Service may use Cookies.</li><br>
   <li><b>Web Beacons.</b> Certain sections of our Service and our emails may contain small 
   electronic files known as web beacons (also referred to as clear gifs, pixel tags, 
   and single-pixel gifs) that permit the Company, for example, to count users who have 
   visited those pages or opened an email and for other related website statistics
   (for example, recording the popularity of a certain section and verifying system 
   and server integrity).</li></h4><br><br>
   
   
   <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Retention of Your Personal
   Data</b></h1>
   <h4 style= "font-size:30;">The Company will retain Your Personal Data only for as long as 
   is necessary for the purposes set out in this Privacy Policy. We will retain and use Your 
   Personal Data to the extent necessary to comply with our legal obligations (for example, 
   if we are required to retain your data to comply with applicable laws), resolve disputes, 
   and enforce our legal agreements and policies.<br><br>

   The Company will also retain Usage Data for internal analysis purposes. Usage Data is 
   generally retained for a shorter period of time, except when this data is used to strengthen
   the security or to improve the functionality of Our Service, or We are legally obligated to 
   retain this data for longer time periods.</h4><br><br>
   
   <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Transfer of Your Personal Data</b></h1>
   <h4 style= "font-size:30;">Your information, including Personal Data, is processed at the Company’s
   operating offices and in any other places where the parties involved in the processing are
   located. It means that this information may be transferred to — and maintained on — 
   computers located outside of Your state, province, country or other governmental 
   jurisdiction where the data protection laws may differ than those from Your jurisdiction.<br><br>
   
   Your consent to this Privacy Policy followed by Your submission of such information 
   represents Your agreement to that transfer.<br><br>
    
   The Company will take all steps reasonably necessary to ensure that Your data is treated
   securely and in accordance with this Privacy Policy and no transfer of Your Personal Data 
   will take place to an organization or a country unless there are adequate controls in place
   including the security of Your data and other personal information.<br><br></h4>
   
   
   <h1 style="font-size:40px;color: #006699; padding-bottom:25px"><b>Delete Your Personal Data</h1>
	<h4 style= "font-size:30;">You have the right to delete or request that We assist in 
	deleting the Personal Data that We have collected about You.<br><br>
	Our Service may give You the ability to delete certain information about You from within 
	the Service.<br><br>
	You may update, amend, or delete Your information at any time by signing in to Your Account,
	if you have one, and visiting the account settings section that allows you to manage Your 
	personal information. You may also contact Us to request access to, correct, or delete any
	personal information that You have provided to Us.<br><br>
	Please note, however, that We may need to retain certain information when we have a legal
	obligation or lawful basis to do so.<br><br>
	
</div>
</body>
</html>
<?php
	include_once('footer.php');
?>